name: Update README
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: redyf
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MSG: ":zap: Update README with the recent activity"
          MAX_LINES: 5
          TARGET_FILE: README.md
          EMPTY_COMMIT_MSG: ":memo: empty commit to keep workflow active after 60 days of no activity"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
